name: "Docker Compose Publishing Tag By Services"
author: "Florian Amette (F4K)"
description: "All services from a docker compose file published under a single Docker Hub repository, with service tagged using its name."
branding:
  icon: "arrow-right-circle"
  color: "red"
inputs:
  docker_compose_files:
    description: "Docker-compose files to use (space-separated, e.g., 'docker-compose.yml docker-compose.ci.yml'). The action will automatically add -f flags."
    required: false
    default: "docker-compose.yml"
  docker_hub_username:
    description: "Docker Hub username (required for pushing to Docker Hub)"
    required: true
  docker_hub_personal_token:
    description: "Docker Hub Personal Access Token (used for README updates, and as fallback for pushing images if docker_hub_org_token is not provided)"
    required: false
    default: ""
  docker_hub_org_token:
    description: "Docker Hub organization/user access token or password (optional, defaults to docker_hub_personal_token if not provided)"
    required: false
    default: ""
  docker_hub_org_name:
    description: "Docker Hub organization/namespace name (optional, defaults to docker_hub_username)"
    required: false
    default: ""
  docker_hub_repository:
    description: "Docker Hub repository name. Can be full path (org/repo-name) or just repo-name. If not provided, uses GitHub repository name."
    required: false
    default: ""
  update_readme:
    description: "Enable updating Docker Hub repository README (optional, defaults to false)"
    required: false
    default: "false"
  readme_path:
    description: "Path to the markdown file to use as Docker Hub README (optional, defaults to ./README.md)"
    required: false
    default: "./README.md"

runs:
  using: "composite"
  steps:
    - name: Determine Docker Hub token
      id: docker_token
      shell: bash
      run: |
        if [ -n "${{ inputs.docker_hub_org_token }}" ]; then
          DOCKER_TOKEN="${{ inputs.docker_hub_org_token }}"
        elif [ -n "${{ inputs.docker_hub_personal_token }}" ]; then
          DOCKER_TOKEN="${{ inputs.docker_hub_personal_token }}"
        else
          echo "Error: Either docker_hub_org_token or docker_hub_personal_token must be provided"
          exit 1
        fi
        echo "token=$DOCKER_TOKEN" >> $GITHUB_OUTPUT

    - name: Determine Docker Hub organization name
      id: docker_org
      shell: bash
      run: |
        if [ -n "${{ inputs.docker_hub_org_name }}" ]; then
          DOCKER_HUB_ORG="${{ inputs.docker_hub_org_name }}"
        else
          DOCKER_HUB_ORG="${{ inputs.docker_hub_username }}"
        fi
        DOCKER_HUB_ORG=$(echo "$DOCKER_HUB_ORG" | tr '[:upper:]' '[:lower:]')
        echo "org=$DOCKER_HUB_ORG" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ steps.docker_org.outputs.org }}
        password: ${{ steps.docker_token.outputs.token }}
        registry: docker.io

    - name: Determine Docker Hub repository name
      id: repo_name
      shell: bash
      run: |
        DOCKER_HUB_ORG="${{ steps.docker_org.outputs.org }}"
        if [ -n "${{ inputs.docker_hub_repository }}" ]; then
          REPO_INPUT="${{ inputs.docker_hub_repository }}"
          if echo "$REPO_INPUT" | grep -q '/'; then
            DOCKER_HUB_REPO="$REPO_INPUT"
          else
            DOCKER_HUB_REPO="${DOCKER_HUB_ORG}/${REPO_INPUT}"
          fi
        else
          GITHUB_REPO="${{ github.repository }}"
          REPO_NAME=$(echo "$GITHUB_REPO" | cut -d'/' -f2)
          DOCKER_HUB_REPO="${DOCKER_HUB_ORG}/${REPO_NAME}"
        fi
        DOCKER_HUB_REPO=$(echo "$DOCKER_HUB_REPO" | tr '[:upper:]' '[:lower:]')
        echo "Using Docker Hub organization: $DOCKER_HUB_ORG"
        echo "Using Docker Hub repository: $DOCKER_HUB_REPO"
        echo "docker_hub_repo=$DOCKER_HUB_REPO" >> $GITHUB_OUTPUT

    - name: Process docker-compose files
      id: compose_files
      shell: bash
      run: |
        FILES="${{ inputs.docker_compose_files }}"
        if echo "$FILES" | grep -q "^-f"; then
          COMPOSE_FILES="$FILES"
        else
          COMPOSE_FILES=""
          for FILE in $FILES; do
            if [ -n "$COMPOSE_FILES" ]; then
              COMPOSE_FILES="$COMPOSE_FILES -f $FILE"
            else
              COMPOSE_FILES="-f $FILE"
            fi
          done
        fi
        echo "Using docker-compose files: $COMPOSE_FILES"
        echo "compose_files=$COMPOSE_FILES" >> $GITHUB_OUTPUT

    - name: Parse docker-compose services
      id: parse_services
      shell: bash
      run: |
        set -e
        SERVICES=$(docker compose ${{ steps.compose_files.outputs.compose_files }} config --services)
        echo "Found services: $SERVICES"
        echo "services<<EOF" >> $GITHUB_OUTPUT
        echo "$SERVICES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Get project name
      id: project_name
      shell: bash
      run: |
        PROJECT_NAME=$(docker compose ${{ steps.compose_files.outputs.compose_files }} config --format json 2>/dev/null | grep -o '"name":"[^"]*"' | head -1 | cut -d'"' -f4 || basename "$(pwd)" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-')
        echo "Project name: $PROJECT_NAME"
        echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT

    - name: Identify services to build
      id: buildable_services
      shell: bash
      run: |
        set -e
        SERVICES="${{ steps.parse_services.outputs.services }}"
        BUILDABLE=""
        echo "Checking which services need to be built..."
        for SERVICE in $SERVICES; do
          HAS_BUILD=$(docker compose ${{ steps.compose_files.outputs.compose_files }} config 2>/dev/null | grep -A 50 "^  $SERVICE:" | grep -E "^\s+build:" | head -1 || echo "")
          if [ -n "$HAS_BUILD" ]; then
            echo "✓ Service '$SERVICE' has build configuration - will be built and pushed"
            if [ -n "$BUILDABLE" ]; then
              BUILDABLE="$BUILDABLE $SERVICE"
            else
              BUILDABLE="$SERVICE"
            fi
          else
            echo "✗ Service '$SERVICE' uses external image - will be skipped"
          fi
        done
        if [ -z "$BUILDABLE" ]; then
          echo "Warning: No services found with build configuration"
        else
          echo "Services to build and push: $BUILDABLE"
        fi
        echo "buildable_services<<EOF" >> $GITHUB_OUTPUT
        echo "$BUILDABLE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Build services
      if: steps.buildable_services.outputs.buildable_services != ''
      shell: bash
      run: |
        BUILDABLE_SERVICES="${{ steps.buildable_services.outputs.buildable_services }}"
        if [ -z "$BUILDABLE_SERVICES" ]; then
          echo "No services to build"
          exit 0
        fi
        echo "Building services: $BUILDABLE_SERVICES"
        for SERVICE in $BUILDABLE_SERVICES; do
          echo "Building service: $SERVICE"
          docker compose ${{ steps.compose_files.outputs.compose_files }} build "$SERVICE"
        done
        echo "Build completed successfully"

    - name: Tag and push services
      if: steps.buildable_services.outputs.buildable_services != ''
      shell: bash
      run: |
        set -e
        DOCKER_HUB_REPO="${{ steps.repo_name.outputs.docker_hub_repo }}"
        PROJECT_NAME="${{ steps.project_name.outputs.project_name }}"
        BUILDABLE_SERVICES="${{ steps.buildable_services.outputs.buildable_services }}"
        if [ -z "$BUILDABLE_SERVICES" ]; then
          echo "No services to push"
          exit 0
        fi
        for SERVICE in $BUILDABLE_SERVICES; do
          echo "::group::Processing service: $SERVICE"
          IMAGE_NAME=""
          COMPOSE_IMAGES_OUTPUT=$(docker compose ${{ steps.compose_files.outputs.compose_files }} images "$SERVICE" 2>/dev/null || echo "")
          if [ -n "$COMPOSE_IMAGES_OUTPUT" ]; then
            IMAGE_NAME=$(echo "$COMPOSE_IMAGES_OUTPUT" | grep -v "CONTAINER" | grep -v "^$" | awk 'NR>1 {print $1":"$2; exit}' | head -1 || echo "")
            if [ -z "$IMAGE_NAME" ] || [ "$IMAGE_NAME" = ":" ]; then
              IMAGE_NAME=$(echo "$COMPOSE_IMAGES_OUTPUT" | grep -v "CONTAINER" | grep -v "^$" | awk 'NR>1 {print $1; exit}' | head -1 || echo "")
            fi
          fi
          if [ -z "$IMAGE_NAME" ] || [ "$IMAGE_NAME" = "null" ]; then
            IMAGE_NAME=$(docker compose ${{ steps.compose_files.outputs.compose_files }} config 2>/dev/null | grep -A 30 "^  $SERVICE:" | grep -E "^\s+image:" | head -1 | sed 's/.*image:[[:space:]]*//' | tr -d '"' | xargs || echo "")
          fi
          if [ -z "$IMAGE_NAME" ] || [ "$IMAGE_NAME" = "null" ]; then
            for PATTERN in "${PROJECT_NAME}-${SERVICE}:latest" "${PROJECT_NAME}_${SERVICE}:latest" "${PROJECT_NAME}-${SERVICE}" "${PROJECT_NAME}_${SERVICE}"; do
              if docker image inspect "$PATTERN" >/dev/null 2>&1; then
                IMAGE_NAME="$PATTERN"
                break
              fi
            done
          fi
          if [ -z "$IMAGE_NAME" ] || [ "$IMAGE_NAME" = "null" ]; then
            echo "Searching for image containing service name: $SERVICE"
            IMAGE_NAME=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -iE "(^|/)$SERVICE(:|$)" | head -1 || echo "")
          fi
          if [ -z "$IMAGE_NAME" ] || [ "$IMAGE_NAME" = "null" ]; then
            echo "Error: Could not determine image name for service $SERVICE"
            echo "Available images:"
            docker images
            exit 1
          fi
          if ! docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
            echo "Error: Image $IMAGE_NAME does not exist"
            echo "Available images:"
            docker images
            exit 1
          fi
          echo "Found image: $IMAGE_NAME"
          DOCKER_HUB_IMAGE="${DOCKER_HUB_REPO}:${SERVICE}"
          echo "Tagging $IMAGE_NAME as $DOCKER_HUB_IMAGE"
          docker tag "$IMAGE_NAME" "$DOCKER_HUB_IMAGE"
          echo "Pushing $DOCKER_HUB_IMAGE to Docker Hub..."
          docker push "$DOCKER_HUB_IMAGE"
          echo "Successfully pushed $DOCKER_HUB_IMAGE"
          echo "::endgroup::"
        done
        echo "All buildable services have been built and pushed to Docker Hub"

    - name: Update Docker Hub README
      if: inputs.update_readme == 'true' && inputs.docker_hub_personal_token != '' && inputs.docker_hub_username != ''
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_personal_token }}
        repository: ${{ steps.repo_name.outputs.docker_hub_repo }}
        readme-filepath: ${{ inputs.readme_path }}
